const ACTIONS = {
    ADD_COMPETITIONS: 'ADD_COMPETITIONS',
    ADD_MY_COMPETITIONS: 'ADD_MY_COMPETITIONS',
    ADD_TY_MY_COMPETITIONS: 'ADD_TY_MY_COMPETITIONS',
    DELETE_COMPETITIONS: 'COMPETITIONS'
}

export default ACTIONS